apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: myapp
  labels:
    app: frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: waelaissi/front:latest
        ports:
         - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  namespace: myapp
  labels:
    app: frontend-app
spec:
  type: NodePort # Change this to LoadBalancer if available
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend-app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: myapp
  labels:
    app: frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: waelaissi/front:latest
        ports:
         - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  namespace: myapp
  labels:
    app: frontend-app
spec:
  type: NodePort # Change this to LoadBalancer if available
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend-app
