apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-spring-app-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-spring-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-spring-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
      containers:
          - name: {{ .Release.Name }}-spring-app-container
            image: {{ .Values.springApp.image.repository }}:{{ .Values.springApp.image.tag }}
            resources:
              requests:
                cpu: "300m"
              limits:
                cpu: "500m"
            imagePullPolicy: {{ .Values.springApp.image.pullPolicy }}
            ports:
              - containerPort: 8089
            env:
              - name: SPRING_DATASOURCE_URL
                value: {{ include "my-spring-app.fullMySQLConnectionURL" . | quote }}
              - name: SPRING_DATASOURCE_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-mysql-username
                    key: username
              - name: SPRING_DATASOURCE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-mysql-password
                    key: password
